### PR TITLE
Add files to commit via hooks

### PR DESCRIPTION
**Pull request by j-walker23**
This changes the isCleanRepository to pass if any changed files are staged

### CODE REVIEW

**Comment by tobiastom** [comment]
Is there anything I can help to merge this? Maybe add an additional option to make this feature opt in?

**Comment by j-walker23** [comment]
Holy crap. This is literally so old i don't even remember doing this. Literally no part of this i remember! Man, getting old sucks.

**Comment by tobiastom** [comment]
@mikaelbr Any change this could be merged somehow?

**Comment by tobiastom** [comment]
Just for the record: my use case is the following: I [keep a changelog](http://keepachangelog.com) which has an unreleased section at the top. To create a new release I now have to change the file and commit this as a separate commit. After that I can run `mversion` to release and tag it. I'd like to avoid the first commit.

**Comment by mikaelbr** [comment]
@tobiastom Merged now. You can check out the master branch (install thorugh `npm i -g mikaelbr/mversion`). If everything looks good, I'll publish a new version.

**Comment by tobiastom** [comment]
@mikaelbr Works perfectly for me. Thank you very much for this merge!

**Comment by tobiastom** [comment]
@mikaelbr Any chance we can get a new release of mversion? :)

**Comment by mikaelbr** [comment]
Sorry 😨 

Fixed!

```
+ mversion@1.13.0
```

**Pull request merged**
